#!/bin/bash
#SBATCH -J DEF_MULTIVIEW
#SBATCH -N 1
#SBATCH -n 64
#SBATCH -t 1-00:00
#SBATCH -p general,serial_requeue
#SBATCH --mem=128000
#SBATCH -o step_3.out
#SBATCH -e step_3.err
export DISPLAY=:4
Xvfb $DISPLAY -auth /dev/null &
/n/home11/jhoffmann/Fiji/Fiji.app/ImageJ-linux64 --memory=128000m -macro TESTRUN3.ijm
/n/home11/jhoffmann/Fiji/Fiji.app/ImageJ-linux64 --memory=128000m -macro quit.ijm
echo DONE WITH DETECT AND REGISTER>>LOG
