#!/bin/bash
#SBATCH -J CZI_2_TIF
#SBATCH -N 1
#SBATCH -n 20
#SBATCH -t 0-10:00
#SBATCH -p general,serial_requeue
#SBATCH --mem=32000
#SBATCH -o step_1.out
#SBATCH -e step_1.err
export DISPLAY=:11
Xvfb $DISPLAY -auth /dev/null &
echo "STARTING CZI CONVERSION">>"LOG"
/n/home11/jhoffmann/Fiji/Fiji.app/ImageJ-linux64 --memory=32000m -macro ./TESTRUN1.ijm
/n/home11/jhoffmann/Fiji/Fiji.app/ImageJ-linux64 --memory=32000m -macro ./quit.ijm
echo "FINISHED CZI CONVERSION">>"LOG"
